server:
  port: 8084

spring:
  application:
    name: memberService
  driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.153.128:3306/gulimall_ums?serverTimezone=UTC&characterEncoding=UTF8
      username: root
      password: 122964
  cloud:
    nacos:
      server-addr: 192.168.153.128:8849 # nacos地址
      discovery:
        namespace: 20628f6c-4f40-43e4-a3a1-23354741e2c3
        group: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: com.keda.gulimall.member.dao # 配置别名包
  mapper-locations: classpath:/mapper/*/*.xml # 配置.xml文件的路径
