server:
  port: 8085

spring:
  application:
    name: orderService
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.153.128:3306/gulimall_oms?serverTimezone=UTC&characterEncoding=UTF8
      username: root
      password: 122964

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: com.keda.gulimall.order.dao # 配置别名包
  mapper-locations: classpath:/mapper/*/*.xml # 配置.xml文件的路径
