server:
  port: 8088

spring:
  application:
    name: ware-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.153.128:3306/gulimall_wms?serverTimezone=UTC&characterEncoding=UTF8
      username: root
      password: 122964
  cloud:
    nacos:
      server-addr: 192.168.153.128:8849 # nacos地址
      discovery:
        namespace: f0e965ab-d760-4f3e-aa80-d881b5ef84e3
        group: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.keda.gulimall.ware.dao # 配置别名包
  mapper-locations: classpath:/mapper/*/*.xml # 配置.xml文件的路径

