server:
  port: 8082
#
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.153.128:3306/gulimall_pms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
#      username: root
#      password: 122964
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.153.128
    port: 6379
  cache:
    # 缓存类型
    type: redis
    redis:
      time-to-live: 3600000
      # 是否使用前缀
      use-key-prefix: true
      # 是否缓存空值，防止缓存穿透
      cache-null-values: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: com.keda.gulimall.goods.dao # 配置别名包
  mapper-locations: classpath:/mapper/*/*.xml # 配置.xml文件的路径

logging:
  level:
    org.apache.ibatis: info
    org.mybatis.spring.SqlSessionFactoryBean: info
    sql: info


